import type { UseListingApprovalRecordActionsParams } from './listingApprovalRecordActionTypes';
import { useListingApprovalPersistenceActions } from './useListingApprovalPersistenceActions';
import { useListingApprovalPublishingActions } from './useListingApprovalPublishingActions';

export function useListingApprovalRecordActions({
  selectedRecord,
  approvalChannel,
  allFieldNames,
  approvedFieldName,
  actualFieldNames,
  tableReference,
  tableName,
  formValues,
  setFormValue,
  setDerivedFormValue,
  hydrateForm,
  saveRecord,
  bodyHtmlPreview,
  ebayBodyHtmlSaveFieldName,
  shouldForceEbayBodyHtmlSave,
  combinedSharedKeyFeaturesFieldName,
  combinedEbayTestingNotesFieldName,
  priceFieldName,
  createShopifyDraftOnApprove,
  shopifyApprovalPreview,
  loadShopifyApprovalPreviewNow,
  syncExistingShopifyListing,
  describeShopifyCreateError,
  resolveShopifyCategoryId,
  upsertShopifyProductWithCollectionFallback,
  canUpdateApprovedShopifyListing,
  hasMissingShopifyRequiredFields,
  hasMissingEbayRequiredFields,
  isShopifyPublishBlockedByAuctionFormat,
  missingShopifyRequiredFieldLabels,
  missingEbayRequiredFieldLabels,
  changedFieldNames,
  approvalPublishSource,
  mergedDraftSourceFields,
  workflowPublishSummary,
  onBackToList,
  pushInlineActionNotice,
  requestConfirmation,
}: UseListingApprovalRecordActionsParams) {
  const { handleResetData, handleSaveUpdates } = useListingApprovalPersistenceActions({
    selectedRecord,
    approvalChannel,
    allFieldNames,
    approvedFieldName,
    actualFieldNames,
    tableReference,
    tableName,
    formValues,
    setFormValue,
    hydrateForm,
    saveRecord,
    bodyHtmlPreview,
    ebayBodyHtmlSaveFieldName,
    shouldForceEbayBodyHtmlSave,
    combinedSharedKeyFeaturesFieldName,
    combinedEbayTestingNotesFieldName,
    priceFieldName,
    pushInlineActionNotice,
    changedFieldNames,
    requestConfirmation,
  });
  const { approving, pushingTarget, handlePrimaryAction, runCombinedPush } = useListingApprovalPublishingActions({
    selectedRecord,
    approvalChannel,
    actualFieldNames,
    approvedFieldName,
    tableReference,
    tableName,
    formValues,
    setFormValue,
    setDerivedFormValue,
    saveRecord,
    createShopifyDraftOnApprove,
    shopifyApprovalPreview,
    loadShopifyApprovalPreviewNow,
    syncExistingShopifyListing,
    describeShopifyCreateError,
    resolveShopifyCategoryId,
    upsertShopifyProductWithCollectionFallback,
    canUpdateApprovedShopifyListing,
    hasMissingShopifyRequiredFields,
    hasMissingEbayRequiredFields,
    isShopifyPublishBlockedByAuctionFormat,
    missingShopifyRequiredFieldLabels,
    missingEbayRequiredFieldLabels,
    approvalPublishSource,
    mergedDraftSourceFields,
    workflowPublishSummary,
    onBackToList,
    pushInlineActionNotice,
    requestConfirmation,
  });

  return {
    approving,
    pushingTarget,
    handlePrimaryAction,
    handleResetData,
    handleSaveUpdates,
    runCombinedPush,
  };
}