import type { UseListingApprovalRecordActionsParams } from './listingApprovalRecordActionTypes';
import { useListingApprovalApproveAction } from './useListingApprovalApproveAction';
import { useListingApprovalPublishActions } from './useListingApprovalPublishActions';
import { useListingApprovalSaveActions } from './useListingApprovalSaveActions';

export function useListingApprovalRecordActions({
  selectedRecord,
  approvalChannel,
  allFieldNames,
  approvedFieldName,
  actualFieldNames,
  tableReference,
  tableName,
  formValues,
  setFormValue,
  hydrateForm,
  saveRecord,
  bodyHtmlPreview,
  ebayBodyHtmlSaveFieldName,
  shouldForceEbayBodyHtmlSave,
  combinedSharedKeyFeaturesFieldName,
  combinedEbayTestingNotesFieldName,
  priceFieldName,
  createShopifyDraftOnApprove,
  shopifyApprovalPreview,
  loadShopifyApprovalPreviewNow,
  syncExistingShopifyListing,
  describeShopifyCreateError,
  resolveShopifyCategoryId,
  upsertShopifyProductWithCollectionFallback,
  canUpdateApprovedShopifyListing,
  hasMissingShopifyRequiredFields,
  hasMissingEbayRequiredFields,
  missingShopifyRequiredFieldLabels,
  missingEbayRequiredFieldLabels,
  approvalPublishSource,
  mergedDraftSourceFields,
  onBackToList,
  pushInlineActionNotice,
}: UseListingApprovalRecordActionsParams) {
  const { pushingTarget, runCombinedPush } = useListingApprovalPublishActions({
    selectedRecord,
    hasMissingShopifyRequiredFields,
    hasMissingEbayRequiredFields,
    missingShopifyRequiredFieldLabels,
    missingEbayRequiredFieldLabels,
    approvalPublishSource,
    mergedDraftSourceFields,
    setFormValue,
    pushInlineActionNotice,
  });
  const { handleResetData, handleSaveUpdates } = useListingApprovalSaveActions({
    selectedRecord,
    approvalChannel,
    allFieldNames,
    approvedFieldName,
    actualFieldNames,
    tableReference,
    tableName,
    formValues,
    setFormValue,
    hydrateForm,
    saveRecord,
    bodyHtmlPreview,
    ebayBodyHtmlSaveFieldName,
    shouldForceEbayBodyHtmlSave,
    combinedSharedKeyFeaturesFieldName,
    combinedEbayTestingNotesFieldName,
    priceFieldName,
    pushInlineActionNotice,
  });
  const { approving, handlePrimaryAction } = useListingApprovalApproveAction({
    selectedRecord,
    approvalChannel,
    actualFieldNames,
    approvedFieldName,
    tableReference,
    tableName,
    formValues,
    setFormValue,
    saveRecord,
    createShopifyDraftOnApprove,
    shopifyApprovalPreview,
    loadShopifyApprovalPreviewNow,
    syncExistingShopifyListing,
    describeShopifyCreateError,
    resolveShopifyCategoryId,
    upsertShopifyProductWithCollectionFallback,
    canUpdateApprovedShopifyListing,
    hasMissingShopifyRequiredFields,
    hasMissingEbayRequiredFields,
    missingShopifyRequiredFieldLabels,
    missingEbayRequiredFieldLabels,
    onBackToList,
    pushInlineActionNotice,
  });

  return {
    approving,
    pushingTarget,
    handlePrimaryAction,
    handleResetData,
    handleSaveUpdates,
    runCombinedPush,
  };
}