import { describe, expect, it, vi } from 'vitest';
import { buildListingApprovalSelectedRecordViewProps } from '@/components/approval/listingApprovalSelectedRecordViewProps';
import type { AirtableRecord } from '@/types/airtable';

function buildRecord(fields: Record<string, unknown>): AirtableRecord {
  return {
    id: 'rec-listing-view-props-1',
    createdTime: '2026-05-18T00:00:00.000Z',
    fields,
  };
}

describe('buildListingApprovalSelectedRecordViewProps', () => {
  it('removes non-listing workflow metadata fields from listing record form props instead of passing them through for hiding', () => {
    const selectedRecord = buildRecord({
      'Additional Items': 'Power cable and shelf card',
      'Customer Cosmetic Notes': 'Customer reported light wear.',
      'Customer Functional Notes': 'Customer said both channels worked.',
      'Customer Inclusion Notes': 'Original accessories included.',
      'Service Notes': 'Controls cleaned and switches exercised.',
      Title: 'McIntosh MA6900',
      Tested: '2026-05-14',
      'Testing Time': '5400',
      'Service Time': '1800',
      'Unqualified Reason': 'Missing serial plate',
      Price: '3499.99',
    });

    const result = buildListingApprovalSelectedRecordViewProps({
      selectedRecord,
      approvalChannel: 'ebay',
      isCombinedApproval: false,
      approvedFieldName: 'Approved',
      titleFieldName: 'Title',
      allFieldNames: [
        'Additional Items',
        'Customer Cosmetic Notes',
        'Customer Functional Notes',
        'Customer Inclusion Notes',
        'Service Notes',
        'Title',
        'Tested',
        'Testing Time',
        'Service Time',
        'Unqualified Reason',
        'Price',
      ],
      formRequiredFieldNames: [],
      formShopifyRequiredFieldNames: [],
      formEbayRequiredFieldNames: [],
      formValues: {
        'Additional Items': 'Power cable and shelf card',
        'Customer Cosmetic Notes': 'Customer reported light wear.',
        'Customer Functional Notes': 'Customer said both channels worked.',
        'Customer Inclusion Notes': 'Original accessories included.',
        'Service Notes': 'Controls cleaned and switches exercised.',
        Title: 'McIntosh MA6900',
        Tested: '2026-05-14',
        'Testing Time': '5400',
        'Service Time': '1800',
        'Unqualified Reason': 'Missing serial plate',
        Price: '3499.99',
      },
      fieldKinds: {
        'Additional Items': 'text',
        'Customer Cosmetic Notes': 'text',
        'Customer Functional Notes': 'text',
        'Customer Inclusion Notes': 'text',
        'Service Notes': 'text',
        Title: 'text',
        Tested: 'text',
        'Testing Time': 'text',
        'Service Time': 'text',
        'Unqualified Reason': 'text',
        Price: 'text',
      },
      listingFormatOptions: [],
      listingDurationOptions: [],
      saving: false,
      setFormValue: vi.fn(),
      setDerivedFormValue: vi.fn(),
      currentPageShopifyBodyHtml: '',
      currentPageShopifyTagValues: [],
      currentPageShopifyCollectionIds: [],
      currentPageShopifyCollectionLabelsById: {},
      combinedDescriptionFieldName: '',
      combinedSharedFieldNames: [],
      combinedRequiredFieldNames: [],
      shopifyRequiredFieldNames: [],
      ebayRequiredFieldNames: [],
      combinedSharedKeyFeaturesFieldName: '',
      combinedSharedKeyFeaturesSyncFieldNames: [],
      combinedEbayTestingNotesFieldName: '',
      drawerSourceFields: {},
      sharedDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedShopifyOnlyFieldNames: [],
      shopifyDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      selectedEbayTemplateId: 'classic',
      setSelectedEbayTemplateId: vi.fn(),
      combinedShopifyBodyHtmlFieldName: '',
      combinedShopifyBodyHtmlValue: '',
      currentPageProductDescriptionResolution: { sourceFieldName: '', sourceType: '' },
      currentPageProductDescription: '',
      currentPageProductCategoryResolution: { sourceFieldName: '', sourceType: '' },
      currentPageCategoryIdResolution: { sourceFieldName: '', value: '' },
      shopifyCategoryLookupValue: '',
      shopifyCategoryResolution: { status: 'idle' },
      isShopifyPayloadPreviewContext: false,
      shopifyProductSetRequest: null,
      combinedEbayOnlyFieldNames: [],
      ebayDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedEbayGeneratedBodyHtml: '',
      ebayCategoryLabelsById: {},
      setEbayCategoryLabelsById: vi.fn(),
      setBodyHtmlPreview: vi.fn(),
      combinedEbayBodyHtmlFieldName: '',
      combinedEbayBodyHtmlValue: '',
      bodyHtmlPreview: '',
      isEbayPayloadPreviewContext: false,
      ebayDraftPayloadBundle: null,
      onOpenOperationalRecord: vi.fn(),
      onOpenTestingForm: vi.fn(),
      onOpenPhotosForm: vi.fn(),
    });

    expect(result.approvalFormFieldsProps.allFieldNames).toEqual(['Title', 'Price']);
    expect(result.approvalFormFieldsProps.writableFieldNames).toEqual(['Title', 'Price']);
  });

  it('removes eBay product aspects fields from listing record form props', () => {
    const selectedRecord = buildRecord({
      Title: 'McIntosh MA6900',
      'eBay Inventory Product Aspects JSON': '{"Brand":["McIntosh"]}',
      Categories: '3276',
    });

    const result = buildListingApprovalSelectedRecordViewProps({
      selectedRecord,
      approvalChannel: 'ebay',
      isCombinedApproval: false,
      approvedFieldName: 'Approved',
      titleFieldName: 'Title',
      allFieldNames: ['Title', 'eBay Inventory Product Aspects JSON', 'Categories'],
      formRequiredFieldNames: [],
      formShopifyRequiredFieldNames: [],
      formEbayRequiredFieldNames: [],
      formValues: {
        Title: 'McIntosh MA6900',
        'eBay Inventory Product Aspects JSON': '{"Brand":["McIntosh"]}',
        Categories: '3276',
      },
      fieldKinds: {
        Title: 'text',
        'eBay Inventory Product Aspects JSON': 'text',
        Categories: 'text',
      },
      listingFormatOptions: [],
      listingDurationOptions: [],
      saving: false,
      setFormValue: vi.fn(),
      setDerivedFormValue: vi.fn(),
      currentPageShopifyBodyHtml: '',
      currentPageShopifyTagValues: [],
      currentPageShopifyCollectionIds: [],
      currentPageShopifyCollectionLabelsById: {},
      combinedDescriptionFieldName: '',
      combinedSharedFieldNames: [],
      combinedRequiredFieldNames: [],
      shopifyRequiredFieldNames: [],
      ebayRequiredFieldNames: [],
      combinedSharedKeyFeaturesFieldName: '',
      combinedSharedKeyFeaturesSyncFieldNames: [],
      combinedEbayTestingNotesFieldName: '',
      drawerSourceFields: {},
      sharedDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedShopifyOnlyFieldNames: [],
      shopifyDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      selectedEbayTemplateId: 'classic',
      setSelectedEbayTemplateId: vi.fn(),
      combinedShopifyBodyHtmlFieldName: '',
      combinedShopifyBodyHtmlValue: '',
      currentPageProductDescriptionResolution: { sourceFieldName: '', sourceType: '' },
      currentPageProductDescription: '',
      currentPageProductCategoryResolution: { sourceFieldName: '', sourceType: '' },
      currentPageCategoryIdResolution: { sourceFieldName: '', value: '' },
      shopifyCategoryLookupValue: '',
      shopifyCategoryResolution: { status: 'idle' },
      isShopifyPayloadPreviewContext: false,
      shopifyProductSetRequest: null,
      combinedEbayOnlyFieldNames: [],
      ebayDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedEbayGeneratedBodyHtml: '',
      ebayCategoryLabelsById: {},
      setEbayCategoryLabelsById: vi.fn(),
      setBodyHtmlPreview: vi.fn(),
      combinedEbayBodyHtmlFieldName: '',
      combinedEbayBodyHtmlValue: '',
      bodyHtmlPreview: '',
      isEbayPayloadPreviewContext: false,
      ebayDraftPayloadBundle: null,
      onOpenOperationalRecord: vi.fn(),
      onOpenTestingForm: vi.fn(),
      onOpenPhotosForm: vi.fn(),
    });

    expect(result.approvalFormFieldsProps.allFieldNames).toEqual(['Title', 'Categories']);
    expect(result.approvalFormFieldsProps.writableFieldNames).toEqual(['Title', 'Categories']);
  });

  it('removes Status from listing record form props', () => {
    const selectedRecord = buildRecord({
      Title: 'McIntosh MA6900',
      Status: "Photo'd",
      Categories: '3276',
    });

    const result = buildListingApprovalSelectedRecordViewProps({
      selectedRecord,
      approvalChannel: 'ebay',
      isCombinedApproval: false,
      approvedFieldName: 'Approved',
      titleFieldName: 'Title',
      allFieldNames: ['Title', 'Status', 'Categories'],
      formRequiredFieldNames: [],
      formShopifyRequiredFieldNames: [],
      formEbayRequiredFieldNames: [],
      formValues: {
        Title: 'McIntosh MA6900',
        Status: "Photo'd",
        Categories: '3276',
      },
      fieldKinds: {
        Title: 'text',
        Status: 'text',
        Categories: 'text',
      },
      listingFormatOptions: [],
      listingDurationOptions: [],
      saving: false,
      setFormValue: vi.fn(),
      setDerivedFormValue: vi.fn(),
      currentPageShopifyBodyHtml: '',
      currentPageShopifyTagValues: [],
      currentPageShopifyCollectionIds: [],
      currentPageShopifyCollectionLabelsById: {},
      combinedDescriptionFieldName: '',
      combinedSharedFieldNames: [],
      combinedRequiredFieldNames: [],
      shopifyRequiredFieldNames: [],
      ebayRequiredFieldNames: [],
      combinedSharedKeyFeaturesFieldName: '',
      combinedSharedKeyFeaturesSyncFieldNames: [],
      combinedEbayTestingNotesFieldName: '',
      drawerSourceFields: {},
      sharedDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedShopifyOnlyFieldNames: [],
      shopifyDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      selectedEbayTemplateId: 'classic',
      setSelectedEbayTemplateId: vi.fn(),
      combinedShopifyBodyHtmlFieldName: '',
      combinedShopifyBodyHtmlValue: '',
      currentPageProductDescriptionResolution: { sourceFieldName: '', sourceType: '' },
      currentPageProductDescription: '',
      currentPageProductCategoryResolution: { sourceFieldName: '', sourceType: '' },
      currentPageCategoryIdResolution: { sourceFieldName: '', value: '' },
      shopifyCategoryLookupValue: '',
      shopifyCategoryResolution: { status: 'idle' },
      isShopifyPayloadPreviewContext: false,
      shopifyProductSetRequest: null,
      combinedEbayOnlyFieldNames: [],
      ebayDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedEbayGeneratedBodyHtml: '',
      ebayCategoryLabelsById: {},
      setEbayCategoryLabelsById: vi.fn(),
      setBodyHtmlPreview: vi.fn(),
      combinedEbayBodyHtmlFieldName: '',
      combinedEbayBodyHtmlValue: '',
      bodyHtmlPreview: '',
      isEbayPayloadPreviewContext: false,
      ebayDraftPayloadBundle: null,
      onOpenOperationalRecord: vi.fn(),
      onOpenTestingForm: vi.fn(),
      onOpenPhotosForm: vi.fn(),
    });

    expect(result.approvalFormFieldsProps.allFieldNames).toEqual(['Title', 'Categories']);
    expect(result.approvalFormFieldsProps.writableFieldNames).toEqual(['Title', 'Categories']);
  });

  it('keeps the derived shipping method on the eBay listing page', () => {
    const selectedRecord = buildRecord({
      Title: 'McIntosh MA6900',
      '__Shipping Services__': 'FedEx Ground',
    });

    const result = buildListingApprovalSelectedRecordViewProps({
      selectedRecord,
      approvalChannel: 'ebay',
      isCombinedApproval: false,
      approvedFieldName: 'Approved',
      titleFieldName: 'Title',
      allFieldNames: ['Title', '__Shipping Services__'],
      formRequiredFieldNames: [],
      formShopifyRequiredFieldNames: [],
      formEbayRequiredFieldNames: [],
      formValues: {
        Title: 'McIntosh MA6900',
        '__Shipping Services__': 'FedEx Ground',
      },
      fieldKinds: {
        Title: 'text',
        '__Shipping Services__': 'text',
      },
      listingFormatOptions: [],
      listingDurationOptions: [],
      saving: false,
      setFormValue: vi.fn(),
      setDerivedFormValue: vi.fn(),
      currentPageShopifyBodyHtml: '',
      currentPageShopifyTagValues: [],
      currentPageShopifyCollectionIds: [],
      currentPageShopifyCollectionLabelsById: {},
      combinedDescriptionFieldName: '',
      combinedSharedFieldNames: [],
      combinedRequiredFieldNames: [],
      shopifyRequiredFieldNames: [],
      ebayRequiredFieldNames: [],
      combinedSharedKeyFeaturesFieldName: '',
      combinedSharedKeyFeaturesSyncFieldNames: [],
      combinedEbayTestingNotesFieldName: '',
      drawerSourceFields: {},
      sharedDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedShopifyOnlyFieldNames: [],
      shopifyDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      selectedEbayTemplateId: 'classic',
      setSelectedEbayTemplateId: vi.fn(),
      combinedShopifyBodyHtmlFieldName: '',
      combinedShopifyBodyHtmlValue: '',
      currentPageProductDescriptionResolution: { sourceFieldName: '', sourceType: '' },
      currentPageProductDescription: '',
      currentPageProductCategoryResolution: { sourceFieldName: '', sourceType: '' },
      currentPageCategoryIdResolution: { sourceFieldName: '', value: '' },
      shopifyCategoryLookupValue: '',
      shopifyCategoryResolution: { status: 'idle' },
      isShopifyPayloadPreviewContext: false,
      shopifyProductSetRequest: null,
      combinedEbayOnlyFieldNames: [],
      ebayDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedEbayGeneratedBodyHtml: '',
      ebayCategoryLabelsById: {},
      setEbayCategoryLabelsById: vi.fn(),
      setBodyHtmlPreview: vi.fn(),
      combinedEbayBodyHtmlFieldName: '',
      combinedEbayBodyHtmlValue: '',
      bodyHtmlPreview: '',
      isEbayPayloadPreviewContext: false,
      ebayDraftPayloadBundle: null,
      onOpenOperationalRecord: vi.fn(),
      onOpenTestingForm: vi.fn(),
      onOpenPhotosForm: vi.fn(),
    });

    expect(result.approvalFormFieldsProps.allFieldNames).toEqual(['Title', '__Shipping Services__']);
    expect(result.approvalFormFieldsProps.writableFieldNames).toEqual(['Title', '__Shipping Services__']);
  });

  it('removes shipping method from listing record form props', () => {
    const selectedRecord = buildRecord({
      Title: 'McIntosh MA6900',
      'Shipping Method': 'Freight',
      Categories: '3276',
    });

    const result = buildListingApprovalSelectedRecordViewProps({
      selectedRecord,
      approvalChannel: 'ebay',
      isCombinedApproval: false,
      approvedFieldName: 'Approved',
      titleFieldName: 'Title',
      allFieldNames: ['Title', 'Shipping Method', 'Categories'],
      formRequiredFieldNames: [],
      formShopifyRequiredFieldNames: [],
      formEbayRequiredFieldNames: [],
      formValues: {
        Title: 'McIntosh MA6900',
        'Shipping Method': 'Freight',
        Categories: '3276',
      },
      fieldKinds: {
        Title: 'text',
        'Shipping Method': 'text',
        Categories: 'text',
      },
      listingFormatOptions: [],
      listingDurationOptions: [],
      saving: false,
      setFormValue: vi.fn(),
      setDerivedFormValue: vi.fn(),
      currentPageShopifyBodyHtml: '',
      currentPageShopifyTagValues: [],
      currentPageShopifyCollectionIds: [],
      currentPageShopifyCollectionLabelsById: {},
      combinedDescriptionFieldName: '',
      combinedSharedFieldNames: [],
      combinedRequiredFieldNames: [],
      shopifyRequiredFieldNames: [],
      ebayRequiredFieldNames: [],
      combinedSharedKeyFeaturesFieldName: '',
      combinedSharedKeyFeaturesSyncFieldNames: [],
      combinedEbayTestingNotesFieldName: '',
      drawerSourceFields: {},
      sharedDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedShopifyOnlyFieldNames: [],
      shopifyDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      selectedEbayTemplateId: 'classic',
      setSelectedEbayTemplateId: vi.fn(),
      combinedShopifyBodyHtmlFieldName: '',
      combinedShopifyBodyHtmlValue: '',
      currentPageProductDescriptionResolution: { sourceFieldName: '', sourceType: '' },
      currentPageProductDescription: '',
      currentPageProductCategoryResolution: { sourceFieldName: '', sourceType: '' },
      currentPageCategoryIdResolution: { sourceFieldName: '', value: '' },
      shopifyCategoryLookupValue: '',
      shopifyCategoryResolution: { status: 'idle' },
      isShopifyPayloadPreviewContext: false,
      shopifyProductSetRequest: null,
      combinedEbayOnlyFieldNames: [],
      ebayDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedEbayGeneratedBodyHtml: '',
      ebayCategoryLabelsById: {},
      setEbayCategoryLabelsById: vi.fn(),
      setBodyHtmlPreview: vi.fn(),
      combinedEbayBodyHtmlFieldName: '',
      combinedEbayBodyHtmlValue: '',
      bodyHtmlPreview: '',
      isEbayPayloadPreviewContext: false,
      ebayDraftPayloadBundle: null,
      onOpenOperationalRecord: vi.fn(),
      onOpenTestingForm: vi.fn(),
      onOpenPhotosForm: vi.fn(),
    });

    expect(result.approvalFormFieldsProps.allFieldNames).toEqual(['Title', 'Categories']);
    expect(result.approvalFormFieldsProps.writableFieldNames).toEqual(['Title', 'Categories']);
  });

  it('removes Shopify variant barcode from listing record form props', () => {
    const selectedRecord = buildRecord({
      Title: 'McIntosh MA6900',
      'Shopify Variant Barcode': 'MCINTOSH-MA6900',
      Vendor: 'McIntosh',
    });

    const result = buildListingApprovalSelectedRecordViewProps({
      selectedRecord,
      approvalChannel: 'shopify',
      isCombinedApproval: false,
      approvedFieldName: 'Approved',
      titleFieldName: 'Title',
      allFieldNames: ['Title', 'Shopify Variant Barcode', 'Vendor'],
      formRequiredFieldNames: [],
      formShopifyRequiredFieldNames: [],
      formEbayRequiredFieldNames: [],
      formValues: {
        Title: 'McIntosh MA6900',
        'Shopify Variant Barcode': 'MCINTOSH-MA6900',
        Vendor: 'McIntosh',
      },
      fieldKinds: {
        Title: 'text',
        'Shopify Variant Barcode': 'text',
        Vendor: 'text',
      },
      listingFormatOptions: [],
      listingDurationOptions: [],
      saving: false,
      setFormValue: vi.fn(),
      setDerivedFormValue: vi.fn(),
      currentPageShopifyBodyHtml: '',
      currentPageShopifyTagValues: [],
      currentPageShopifyCollectionIds: [],
      currentPageShopifyCollectionLabelsById: {},
      combinedDescriptionFieldName: '',
      combinedSharedFieldNames: [],
      combinedRequiredFieldNames: [],
      shopifyRequiredFieldNames: [],
      ebayRequiredFieldNames: [],
      combinedSharedKeyFeaturesFieldName: '',
      combinedSharedKeyFeaturesSyncFieldNames: [],
      combinedEbayTestingNotesFieldName: '',
      drawerSourceFields: {},
      sharedDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedShopifyOnlyFieldNames: [],
      shopifyDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      selectedEbayTemplateId: 'classic',
      setSelectedEbayTemplateId: vi.fn(),
      combinedShopifyBodyHtmlFieldName: '',
      combinedShopifyBodyHtmlValue: '',
      currentPageProductDescriptionResolution: { sourceFieldName: '', sourceType: '' },
      currentPageProductDescription: '',
      currentPageProductCategoryResolution: { sourceFieldName: '', sourceType: '' },
      currentPageCategoryIdResolution: { sourceFieldName: '', value: '' },
      shopifyCategoryLookupValue: '',
      shopifyCategoryResolution: { status: 'idle' },
      isShopifyPayloadPreviewContext: false,
      shopifyProductSetRequest: null,
      combinedEbayOnlyFieldNames: [],
      ebayDrawerRequiredStatus: { hasRequired: false, allFilled: true },
      combinedEbayGeneratedBodyHtml: '',
      ebayCategoryLabelsById: {},
      setEbayCategoryLabelsById: vi.fn(),
      setBodyHtmlPreview: vi.fn(),
      combinedEbayBodyHtmlFieldName: '',
      combinedEbayBodyHtmlValue: '',
      bodyHtmlPreview: '',
      isEbayPayloadPreviewContext: false,
      ebayDraftPayloadBundle: null,
      onOpenOperationalRecord: vi.fn(),
      onOpenTestingForm: vi.fn(),
      onOpenPhotosForm: vi.fn(),
    });

    expect(result.approvalFormFieldsProps.allFieldNames).toEqual(['Title', 'Vendor']);
    expect(result.approvalFormFieldsProps.writableFieldNames).toEqual(['Title', 'Vendor']);
  });
});
