export const primaryActionButtonClass = 'inline-flex items-center justify-center rounded-xl bg-gradient-to-r from-[var(--accent)] to-blue-500 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_10px_24px_rgba(17,32,49,0.12)] transition hover:-translate-y-0.5 hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:translate-y-0';

export const secondaryActionButtonClass = 'inline-flex items-center justify-center rounded-xl border border-[var(--line)] bg-[var(--panel)] px-4 py-2.5 text-sm font-semibold text-[var(--ink)] shadow-[0_8px_24px_rgba(17,32,49,0.05)] transition hover:-translate-y-0.5 hover:border-sky-300 hover:bg-[var(--line)] disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:translate-y-0';

export const accentActionButtonClass = 'inline-flex items-center justify-center rounded-xl bg-gradient-to-r from-teal-700 to-teal-500 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_10px_24px_rgba(17,32,49,0.12)] transition hover:-translate-y-0.5 hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:translate-y-0';
export const smallSecondaryActionButtonClass = 'inline-flex items-center justify-center rounded-xl border border-[var(--line)] bg-[var(--bg)] px-3 py-1.5 text-xs font-medium text-[var(--muted)] transition hover:border-[var(--accent)] hover:bg-[var(--line)] hover:text-[var(--ink)] disabled:cursor-not-allowed disabled:opacity-60';
export const smallPrimaryActionButtonClass = 'inline-flex items-center justify-center rounded-xl border border-[var(--accent)]/35 bg-[var(--accent)]/10 px-3 py-1.5 text-xs font-medium text-[var(--ink)] transition hover:border-[var(--accent)] hover:bg-[var(--accent)]/15 disabled:cursor-not-allowed disabled:opacity-60';
export const smallSuccessActionButtonClass = 'inline-flex items-center justify-center rounded-xl border border-emerald-400/35 bg-emerald-500/10 px-3 py-1.5 text-xs font-medium text-emerald-100 transition hover:border-emerald-300/60 hover:bg-emerald-500/15 disabled:cursor-not-allowed disabled:opacity-60';
export const compactRowSecondaryActionButtonClass = 'inline-flex items-center justify-center rounded-lg border border-[var(--line)] bg-[var(--panel)]/80 px-2.5 py-1 text-[11px] font-medium text-[var(--ink)] shadow-[inset_0_1px_0_rgba(255,255,255,0.04)] transition hover:border-[var(--accent)]/45 hover:bg-[var(--panel)] disabled:cursor-not-allowed disabled:opacity-60';
export const compactRowPrimaryActionButtonClass = 'inline-flex items-center justify-center rounded-lg border border-[var(--accent)]/20 bg-[var(--accent)]/8 px-2.5 py-1 text-[11px] font-medium text-[var(--ink)] transition hover:border-[var(--accent)]/35 hover:bg-[var(--accent)]/12 disabled:cursor-not-allowed disabled:opacity-60';
