import type { AirtableRecord } from '@/types/airtable';
import type { JotFormSubmission } from '@/types/jotform';
import type { HiFiSharkListing } from '@/types/hifishark';
import type { EbayInventoryItem, EbayOffer } from '@/services/ebay';
import type { EbayPublishedListing } from '@/hooks/useEbayListings';
import type { useDashboardMetrics } from '@/hooks/useDashboardMetrics';
import type { useShopifyProducts } from '@/hooks/useShopifyProducts';
import type { Tab } from '@/app/appNavigation';

export interface AppTabContentProps {
  activeTab: Tab;
  approvalRecordId: string | null;
  userRecordId: string | null;
  navigateToApprovalRecord: (recordId: string, replace?: boolean) => void;
  navigateToApprovalList: (replace?: boolean) => void;
  navigateToUserRecord: (userId: string, replace?: boolean) => void;
  navigateToUsersList: (replace?: boolean) => void;
  navigateToTab: (tab: Tab, replace?: boolean) => void;
  metrics: ReturnType<typeof useDashboardMetrics>;
  accessiblePages: Tab[];
  aiProvider: 'github' | 'openai' | 'none';
  usersCount: number;
  adminCount: number;
  nonEmptyListings: AirtableRecord[];
  atLoading: boolean;
  atError: Error | null;
  products: ReturnType<typeof useShopifyProducts>['products'];
  spLoading: boolean;
  spError: Error | null;
  jfSubmissions: JotFormSubmission[];
  jfLoading: boolean;
  jfPolling: boolean;
  jfError: Error | null;
  jfRefetch: () => void;
  jfLastUpdated: Date | null;
  jfFreshCount: number;
  jfClearFresh: () => void;
  totalNewSubmissions: number;
  approvalLoading: boolean;
  approvalError: string | null;
  approvalTotal: number;
  approvalApproved: number;
  approvalPending: number;
  ebayAuthenticated: boolean;
  ebayRestoringSession: boolean;
  ebayLoading: boolean;
  ebayError: string | null;
  ebayInventoryItems: EbayInventoryItem[];
  ebayOffers: EbayOffer[];
  ebayRecentListings: EbayPublishedListing[];
  ebayTotal: number;
  ebayPublishedCount: number;
  ebayDraftCount: number;
  ebayRefetch: () => void;
  ebayDisconnect: () => void;
  sharkLoading: boolean;
  sharkError: Error | null;
  sharkListings: HiFiSharkListing[];
  sharkSearch: (slug: string) => void;
  currentSlug: string;
}