import { describe, expect, it, vi } from 'vitest';
import { buildDashboardTabViewModel } from '@/app/appTabContentMappers';
import type { AppTabContentProps } from '@/app/appTabContentTypes';

function buildInput(overrides: Partial<AppTabContentProps> = {}): AppTabContentProps {
  return {
    activeTab: 'dashboard',
    jotformReviewGroupId: null,
    incomingGearRecordId: null,
    testingRecordId: null,
    photosRecordId: null,
    inventoryRecordId: null,
    usedGearWorkflowRecordId: null,
    listingsRecordId: null,
    approvalRecordId: null,
    shopifyApprovalRecordId: null,
    userRecordId: null,
    navigateToInventoryRecord: vi.fn(),
    navigateToUsedGearWorkflowRecord: vi.fn(),
    navigateToInventoryList: vi.fn(),
    navigateToInventoryPostPublishBucket: vi.fn(),
    navigateToIncomingGearForm: vi.fn(),
    navigateToTestingForm: vi.fn(),
    navigateToPhotosForm: vi.fn(),
    navigateToListingsRecord: vi.fn(),
    navigateToListingsList: vi.fn(),
    navigateToApprovalRecord: vi.fn(),
    navigateToApprovalList: vi.fn(),
    navigateToShopifyApprovalRecord: vi.fn(),
    navigateToShopifyApprovalList: vi.fn(),
    navigateToUserRecord: vi.fn(),
    navigateToUsersList: vi.fn(),
    navigateToTab: vi.fn(),
    navigateToJotformReviewGroup: vi.fn(),
    runtimeFeatures: {
      jotform: { available: true, message: null, missingEnvNames: [] },
      ebay: { available: true, message: null, missingEnvNames: [] },
      approvalEbay: { available: true, message: null, missingEnvNames: [] },
      approvalShopify: { available: true, message: null, missingEnvNames: [] },
      approvalCombined: { available: true, message: null, missingEnvNames: [] },
    },
    metrics: {
      now: Date.now(),
      thisWeekSubs: [],
      recentSubs: [],
      draftProducts: [],
      activeProducts: [],
      archivedProducts: [],
      acquisitionCost: 0,
      inventoryValue: 0,
      avgAskPrice: 0,
      sellThroughPct: null,
      grossMarginPct: null,
      submissionsTrend: { direction: 'flat', text: 'Flat' },
      dealsTrend: { direction: 'flat', text: 'Flat' },
      acquisitionTrend: { direction: 'flat', text: 'Flat' },
      inventoryTrend: { direction: 'flat', text: 'Flat' },
      salesTrend: { direction: 'flat', text: 'Flat' },
      marginTrend: { direction: 'flat', text: 'Flat' },
      submissionDays: [],
      maxDayCount: 0,
      topBrands: [],
      airtableInventoryValue: 0,
      uniqueAirtableBrands: 0,
      uniqueAirtableTypes: 0,
      componentTypeSummary: [],
      airtableBrandSummary: [],
      airtableDistributorSummary: [],
      airtableTypeTable: [],
      maxComponentTypeCount: 0,
      maxAirtableBrandCount: 0,
      insights: [],
    },
    accessiblePages: ['dashboard', 'inventory'],
    currentUserName: 'Taylor Reviewer',
    aiProvider: 'none',
    usersCount: 0,
    adminCount: 0,
    nonEmptyListings: [],
    displayValue: (value) => String(value ?? ''),
    hasValue: (value) => value !== null && value !== undefined && String(value).trim().length > 0,
    recordTitle: () => '',
    atLoading: false,
    atError: null,
    products: [],
    storeDomain: '',
    spLoading: false,
    spError: null,
    jfSubmissions: [],
    jfLoading: false,
    jfPolling: false,
    jfError: null,
    jfRefetch: vi.fn(),
    jfLastUpdated: null,
    jfFreshCount: 0,
    jfClearFresh: vi.fn(),
    totalNewSubmissions: 0,
    approvalLoading: false,
    approvalError: null,
    approvalTotal: 0,
    approvalApproved: 0,
    approvalPending: 0,
    shopifyApprovalLoading: false,
    shopifyApprovalError: null,
    shopifyApprovalTotal: 0,
    shopifyApprovalApproved: 0,
    shopifyApprovalPending: 0,
    workflowAnalytics: {
      loading: false,
      error: null,
      totalCount: 0,
      pendingReviewCount: 0,
      trashCount: 0,
      progressCount: 0,
      postPublishCount: 0,
      statusCounts: {
        'Pending Review': 0,
        'Unqualified': 0,
        'Accepted - Awaiting Arrival': 0,
        'Accepted - Arrived, Awaiting SKU': 0,
        'Accepted - Arrived, Awaiting Missing Item': 0,
        'Testing and Photography In Progress': 0,
        'Awaiting Pre-Listing Review': 0,
        'Approved for Publish': 0,
        'Listed, Shopify': 0,
        'Listed, eBay': 0,
        'Stale Listing, Shopify': 0,
        'Stale Listing, eBay': 0,
        'Sold - Ready to Ship': 0,
        'Shipped': 0,
      },
      marketplace: {
        shopifyLiveCount: 0,
        shopifyStaleCount: 0,
        ebayLiveCount: 0,
        ebayStaleCount: 0,
        soldReadyCount: 0,
        shippedCount: 0,
      },
      age: {
        pendingReviewAlertCount: 0,
        oldestPendingReviewAgeDays: null,
        progressAlertCount: 0,
        oldestProgressAgeDays: null,
        activeNearStaleCount: 0,
        staleFollowUpCount: 0,
        oldestListedAgeDays: null,
        oldestStaleAgeDays: null,
      },
      lifecycle: {
        averageDaysToSell: null,
        averageDaysToShip: null,
        soldReadyAwaitingShipmentCount: 0,
        oldestSoldReadyAgeDays: null,
      },
      refetch: vi.fn(),
    },
    workflowPostPublishLoading: false,
    workflowPostPublishError: null,
    workflowActiveListingCount: 0,
    workflowStaleListingCount: 0,
    workflowStaleListingUnassignedCount: 0,
    workflowSoldReadyCount: 0,
    workflowSoldReadyUnassignedCount: 0,
    workflowShippedCount: 0,
    ebayAuthenticated: false,
    ebayRestoringSession: false,
    ebayLoading: false,
    ebayError: null,
    ebayRuntimeConfig: null,
    ebayInventoryItems: [],
    ebayOffers: [],
    ebayRecentListings: [],
    ebayTotal: 0,
    ebayPublishedCount: 0,
    ebayDraftCount: 0,
    ebayRefetch: vi.fn(),
    sharkLoading: false,
    sharkError: null,
    sharkListings: [],
    sharkSearch: vi.fn(),
    currentSlug: '',
    ...overrides,
  };
}

describe('buildDashboardTabViewModel', () => {
  it('maps owner-aware post-publish dashboard actions into inventory navigation options', () => {
    const navigateToInventoryPostPublishBucket = vi.fn();
    const viewModel = buildDashboardTabViewModel(buildInput({ navigateToInventoryPostPublishBucket }));

    viewModel.actions.onOpenInventoryPostPublishBucket('sold-ready', 'unassigned');

    expect(navigateToInventoryPostPublishBucket).toHaveBeenCalledWith('sold-ready', { ownerFilter: 'unassigned' });
  });
});