import type { AirtableRecord } from '@/types/airtable';
import type { JotFormSubmission } from '@/types/jotform';
import type { HiFiSharkListing } from '@/types/hifishark';
import type { EbayInventoryItem, EbayOffer } from '@/services/ebay/types';
import type { EbayPublishedListing } from '@/hooks/useEbayListings';
import type { EbayRuntimeConfig } from '@/services/app-api/ebay';
import type { useDashboardMetrics } from '@/hooks/useDashboardMetrics';
import type { useShopifyProducts } from '@/hooks/useShopifyProducts';
import type { Tab } from '@/app/appNavigation';
import type { RuntimeFeatureMap } from '@/config/runtimeCapabilities';
import type { UsedGearWorkflowAnalyticsSnapshotState } from '@/hooks/useUsedGearWorkflowAnalyticsSnapshot';
import type { UsedGearWorkflowDashboardTargetsState } from '@/hooks/useUsedGearWorkflowDashboardTargets';
import type { UsedGearWorkflowPostPublishBucket } from '@/services/usedGearWorkflowLifecycle';
import type { UserRole } from '@/stores/auth/authTypes';

export interface AppTabContentProps {
  activeTab: Tab;
  manualIntakeMode: boolean;
  jotformReviewGroupId: string | null;
  jotformReviewRecordId: string | null;
  jotformDirectoryRecordId: string | null;
  parkingLotArrivalGroupId: string | null;
  parkingLotArrivalRecordId: string | null;
  trashReviewGroupId: string | null;
  trashReviewRecordId: string | null;
  manualIntakeRecordId: string | null;
  testingRecordId: string | null;
  photosRecordId: string | null;
  inventoryRecordId: string | null;
  inventoryPriceEditorRecordId: string | null;
  listingsRecordId: string | null;
  soldReadyListingsRecordId: string | null;
  shippedListingsRecordId: string | null;
  shopifyListingsRecordId: string | null;
  ebayListingsRecordId: string | null;
  userRecordId: string | null;
  navigateToInventoryRecord: (recordId: string, replace?: boolean) => void;
  navigateToInventoryPriceEditor: (recordId: string, replace?: boolean) => void;
  navigateToUsedGearOperationalRecord: (recordId: string, replace?: boolean) => void;
  navigateToInventoryList: (replace?: boolean) => void;
  navigateToInventoryWorkflowView: (
    view: 'pending-review' | 'progress',
    options?: { replace?: boolean; focusedGroupId?: string | null },
  ) => void;
  navigateToInventoryPostPublishBucket: (
    bucket: UsedGearWorkflowPostPublishBucket,
    options?: { replace?: boolean },
  ) => void;
  navigateToManualIntake: (replace?: boolean) => void;
  navigateToCreateIntakeItem: (replace?: boolean) => void;
  navigateToManualIntakeForm: (recordId?: string | null, replace?: boolean) => void;
  navigateToTestingForm: (recordId?: string | null, replace?: boolean) => void;
  navigateToPhotosForm: (recordId?: string | null, replace?: boolean) => void;
  navigateToListingsRecord: (recordId: string, replace?: boolean) => void;
  navigateToSoldReadyListingRecord: (recordId: string, replace?: boolean) => void;
  navigateToShippedListingRecord: (recordId: string, replace?: boolean) => void;
  navigateToListingsList: (replace?: boolean) => void;
  navigateToShopifyRecord: (recordId: string, replace?: boolean) => void;
  navigateToShopifyList: (replace?: boolean) => void;
  navigateToEbayRecord: (recordId: string, replace?: boolean) => void;
  navigateToEbayList: (replace?: boolean) => void;
  navigateToUserRecord: (userId: string, replace?: boolean) => void;
  navigateToUsersList: (replace?: boolean) => void;
  navigateToTab: (tab: Tab, replace?: boolean) => void;
  navigateToParkingLotPendingReviewGroup: (groupId: string, replace?: boolean) => void;
  navigateToPath: (path: string, replace?: boolean) => void;
  runtimeFeatures: RuntimeFeatureMap;
  metrics: ReturnType<typeof useDashboardMetrics>;
  accessiblePages: Tab[];
  currentUserRole: UserRole;
  currentUserName: string;
  aiProvider: 'github' | 'openai' | 'backend' | 'none';
  usersCount: number;
  adminCount: number;
  nonEmptyListings: AirtableRecord[];
  displayValue: (value: unknown) => string;
  hasValue: (value: unknown) => boolean;
  recordTitle: (fields: Record<string, unknown>) => string;
  airtableRefetch: () => Promise<void>;
  atLoading: boolean;
  atError: Error | null;
  products: ReturnType<typeof useShopifyProducts>['products'];
  storeDomain?: string;
  spLoading: boolean;
  spError: Error | null;
  jfSubmissions: JotFormSubmission[];
  jfLoading: boolean;
  jfPolling: boolean;
  jfError: Error | null;
  jfRefetch: () => void;
  jfLastUpdated: Date | null;
  jfFreshCount: number;
  jfClearFresh: () => void;
  approvalLoading: boolean;
  approvalError: string | null;
  approvalTotal: number;
  approvalApproved: number;
  approvalPending: number;
  shopifyApprovalLoading: boolean;
  shopifyApprovalError: string | null;
  shopifyApprovalTotal: number;
  shopifyApprovalApproved: number;
  shopifyApprovalPending: number;
  workflowDashboardTargets: UsedGearWorkflowDashboardTargetsState;
  workflowAnalytics: UsedGearWorkflowAnalyticsSnapshotState;
  workflowPostPublishLoading: boolean;
  workflowPostPublishError: string | null;
  workflowActiveListingCount: number;
  workflowStaleListingCount: number;
  workflowStaleListingMineCount: number;
  workflowStaleListingUnassignedCount: number;
  workflowSoldReadyCount: number;
  workflowSoldReadyMineCount: number;
  workflowSoldReadyUnassignedCount: number;
  workflowShippedCount: number;
  ebayAuthenticated: boolean;
  ebayRestoringSession: boolean;
  ebayLoading: boolean;
  ebayError: string | null;
  ebayRuntimeConfig: EbayRuntimeConfig | null;
  ebayInventoryItems: EbayInventoryItem[];
  ebayOffers: EbayOffer[];
  ebayRecentListings: EbayPublishedListing[];
  ebayTotal: number;
  ebayPublishedCount: number;
  ebayDraftCount: number;
  ebayRefetch: () => void;
  sharkLoading: boolean;
  sharkError: Error | null;
  sharkListings: HiFiSharkListing[];
  sharkSearch: (slug: string) => void;
  currentSlug: string;
}